---
# tasks file for roles/mongodb
#sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
- name: add mongo apt-key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

- name: update repo to add libcurl3
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

- name: install libcurl3
  apt:
    name: libcurl3
    state: present

- name: install mongodb-org
  apt:
    name: mongodb-org
    update_cache: yes
    state: present

- name: config mongodb network interface
  template:
    src: "mongod.conf.j2"
    dest: "/etc/mongod.conf"
  notify: "restart mongodb"
