---
- name: add mongo apt-key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: E162F504A20CDF15827F718D4B7C549A058F8B6B

<<<<<<< HEAD
# mongodb is xenial binary, not fully compatible 
# with bionic, it requires downgrade libcurl4 to libcurl3
# then the curl and ubunut-server will be removed
- name: update repo source for mongodb
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
=======
- name: update repo to add mongodb 4.1 unstable
  shell: echo "deb [ trusted=yes arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.1 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-unstable-4.1.list
>>>>>>> release/v150

- name: install mongodb-org-unstable
  apt:
    name: mongodb-org-unstable
    update_cache: yes
    state: present

- name: config mongodb network interface
  template:
    src: "mongod.conf.j2"
    dest: "/etc/mongod.conf"
  notify: "restart mongodb"
