---
- name: add mongo apt-key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: E162F504A20CDF15827F718D4B7C549A058F8B6B

- name: update repo to add mongodb 4.1 unstable
  shell: echo "deb [ trusted=yes arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.1 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-unstable-4.1.list

- name: install mongodb-org-unstable
  apt:
    name: mongodb-org-unstable
    update_cache: yes
    state: present

- name: config mongodb network interface
  template:
    src: "mongod.conf.j2"
    dest: "/etc/mongod.conf"
  notify: "restart mongodb"

- name: prepare to create swap file
  apt:
    name: dphys-swapfile
    update_cache: yes
    state: present

- name: configure swap file size
  template:
    src: "dphys-swapfile.j2"
    dest: "/etc/dphys-swapfile"
  notify: "restart dpyhs-swapfile"
