---
- name: add mongo apt-key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

# mongodb is xenial binary, not fully compatible 
# with bionic, it requires downgrade libcurl4 to libcurl3
# then the curl and ubunut-server will be removed
- name: update repo source for mongodb
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

- name: install libcurl3
  apt:
    name: libcurl3
    state: present

- name: install mongodb-org
  apt:
    name: mongodb-org
    update_cache: yes
    state: present

- name: config mongodb network interface
  template:
    src: "mongod.conf.j2"
    dest: "/etc/mongod.conf"
  notify: "restart mongodb"
