---
# handlers file for roles/mongodb

- name: restart mongodb
  service:
    name: mongod
    enabled: yes
    state: restarted

- name: restart dpyhs-swapfile
  service:
    name: dphys-swapfile
    enabled: yes
    state: restarted
